name: Backend CI

on:
  push:
    paths:
      - "Cab-Connect-Backend/**"
  pull_request:
    paths:
      - "Cab-Connect-Backend/**"

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Cab-Connect-Backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Cab-Connect-Backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run basic tests
        run: npx vitest run src/tests/basic.test.js
        env:
            NODE_ENV: test

      - name: Run rules tests
        run: npx vitest run src/tests/rules.test.js
        env:  
            NODE_ENV: test

      - name: Run integration tests
        run: npx vitest run src/tests/api.integration.test.js
        env:
            NODE_ENV: test

